WebApplication2/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Models
{
    public class EmpModel
    {
        [Display(Name = "Id")]
        public int Empid { get; set; }

        [Required(ErrorMessage = "First name is required.")]
        //[FullName]
        //[Display(Name = "Name")]
        public string Name { get; set; }

        //[Required(ErrorMessage = "City is required.")]
        //public string City { get; set; }

        //[Required(ErrorMessage = "Address is required.")]
        //public string Address { get; set; }
        public string state { get; set; }
        public string District { get; set; }

        [Required]
        [Display(Name = "Date Of Birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public string DOB { get; set; }
        public List<SelectListItem> StateList {get; set;}

        public List<SelectListItem> DistrictList {get; set;}
    }
}

WebApplication2/Models/StateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication2.Controllers
{
    public class State
    {
        public int StateId { get; set; }
        public string StateName { get; set;}
        
    }
    public class District
    {
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        //public int StateId { get; set; }
    }
}

WebApplication2/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Repository;

namespace WebApplication2.Controllers
{
    public class EmployeeController : Controller
    {
       // GET: Employee/GetAllEmpDetails    
        public ActionResult GetAllEmpDetails()
        {
            EmpRepository EmpRepo = new EmpRepository();
            ModelState.Clear();
            return View(EmpRepo.GetAllEmployees());
        }
        //GET:Employee/AddEmployee
        public ActionResult AddEmployee()
        {
            EmpRepository EmpRepo = new EmpRepository();
            ViewBag.State = EmpRepo.GetAllStates();
            return View();
        }

        //POST:Employee/AddEmployee
        [HttpPost]
        public ActionResult AddEmployee(EmpModel Emp)
        {
            EmpRepository EmpRepo = new EmpRepository();
            ViewBag.State = EmpRepo.GetAllStates();
            //ViewBag.District = EmpRepo.GetDistrictName();//edit
            if (EmpRepo.AddEmployee(Emp))
              {
               ViewBag.Message = "Employee details added sucessfully ";
               ModelState.Clear();
              }
            return View();
          
        }
        //GET: Employee/EditEmpDetails/id
        public ActionResult EditEmpDetails(int id)
        {
            EmpRepository EmpRepo = new EmpRepository();
            var empDetails = EmpRepo.GetAllEmployeesById(id);
            //GetDistrictName(id)
            var states = EmpRepo.GetAllStates();
            var statesItems = new List<SelectListItem>();
            foreach (var state in states) {
                statesItems.Add(new SelectListItem()
                {
                    Text = state.StateName,
                    Value = state.StateId.ToString(),
                    Selected = state.StateId.ToString() == empDetails.state ? true : false
                });
            }
            empDetails.StateList = statesItems;
            //empDetails //for districts 
            var district = EmpRepo.GetDistrictName(empDetails.state);
            var districtItems = new List<SelectListItem>();
            foreach (var dis in district)
            {
                districtItems.Add(new SelectListItem()
                {
                    Text = dis.DistrictName,
                    Value = dis.DistrictId.ToString(),
                    Selected = dis.DistrictId.ToString() == empDetails.District ? true : false
                });
            }
            empDetails.DistrictList = districtItems;
            //ViewBag.State =  EmpRepo.GetAllStates
            return View(empDetails);
        }
        // POST: Employee/EditEmpDetails/id  
        [HttpPost]
        public ActionResult EditEmpDetails(int id, EmpModel obj)
        {
            try
            {
                EmpRepository EmpRepo = new EmpRepository();
                EmpRepo.UpdateEmployee(obj);
                return RedirectToAction("GetAllEmpDetails");
            }
            catch
            {
                return RedirectToAction("GetAllEmpDetails");
            }
        }
        // GET: Employee/DeleteEmp/id   
        public ActionResult DeleteEmp(int id)
        {
            try
            {
                EmpRepository EmpRepo = new EmpRepository();
                if (EmpRepo.DeleteEmployee(id))
                {
                    ViewBag.AlertMsg = "Employee details deleted successfully";

                }
                return RedirectToAction("GetAllEmpDetails");
            }
            catch
            {
                return View();
            }
        }
        //[HttpPost]
        //public JsonResult GetAllStates()
        //{
        //    EmpRepository EmpRepo = new EmpRepository();
        //    var state = EmpRepo.GetAllStates();
        //    ModelState.Clear();
        //    return Json(state, JsonRequestBehavior.AllowGet);
        //}
        //[HttpPost]
        public JsonResult GetAllDistrictByState(String id)
        {
            EmpRepository EmpRepo = new EmpRepository();
            List<District> st = EmpRepo.GetDistrictName(id);
            return Json(st, JsonRequestBehavior.AllowGet);
        }
       
    }
 }

WebApplication2/Views/Employee/AddEmployee.cshtml
@model WebApplication2.Models.EmpModel

@using (Html.BeginForm("AddEmployee", "Employee", FormMethod.Post, new { @id = "addemp", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add Employee</h4>
        <div>
            @Html.ActionLink("Back to Employee List", "GetAllEmpDetails")
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.state, new SelectList(ViewBag.State, "StateId", "StateName"), "Select State", new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.District, new SelectList(""), "Select District", new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", placeholder = "DOB", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green">
                @ViewBag.Message
            </div>
        </div>
    </div>

}
@section Scripts {

    <script type="text/javascript">
        //get district  list by state id
        $("#s").removeAttr('disabled');
        $(document).ready(function () {
            $("#state").on("change", function () {
                $.ajax({
                    url: "/Employee/GetAllDistrictByState",
                    type: "GET",
                    dataType: "json",
                    data: { id: $("#state").val() },
                    success: function (data) {
                        //console.log(data);
                        $("#District").append("<option value='0'>Select District</option>");
                        $.each(data, function (i, val) {
                               $("#District").append("<option value=\"" + val.DistrictId + "\">" + val.DistrictName + "</option>");
                            //$("#District").html("");
                       });
                    }
                })
            })
            //date picker
            $('#DOB').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                maxDate: 0,
                yearRange: "-60:+0"
            });
            //form validation using jquery
            $('#addemp').validate({
                errorClass: 'help-block animation-slideDown', // You can change the animation class for a different entrance animation - check animations page  
                errorElement: 'div',
                errorPlacement: function (error, e) {
                    e.parents('.form-group > div').append(error);
                },
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success has-error').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    e.closest('.form-group').removeClass('has-success has-error');
                    e.closest('.help-block').remove();
                },
                rules: {
                    'Name': {
                        required: true,
                    },

                    'state': {
                        required: true,
                    },

                    'District': {
                        required: true,
                    },
                    'DOB': {
                        required: true,
                    }
                },
                messages: {
                    'Name': 'Name missing',
                    'state': 'select state',
                    'District': 'select district',
                    'DOB': 'dob missing '
                }
            });
        });
      
        
       
         </script>
   
}

WebApplication2/Views/Employee/EditEmpDetails.cshtml
@model WebApplication2.Models.EmpModel
@using (Html.BeginForm("EditEmpDetails", "Employee", method: FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Update Employee Details</h4>
    <hr />
    <div>
        @Html.ActionLink("Back to Details", "GetAllEmpDetails")
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Empid)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
   
   
    <div class="form-group">
        @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.state, Model.StateList, "-state-", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.District, Model.DistrictList, "- District-", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", placeholder = "DOB"} })
            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#state").on("change", function () {
                $.ajax({
                    url: "/Employee/GetAllDistrictByState",
                    type: "GET",
                    dataType: "json",
                    data: { id: $("#state").val() },
                    success: function (data) {
                        console.log(data);
                        $("#District").html("");
                        $("#District").append("<option value='0'>Select District</option>");
                        $.each(data, function (i, val) {
                            $("#District").append("<option value=\"" + val.DistrictId + "\">" + val.DistrictName + "</option>");
                            console.log('district name :', val.DistrictName, 'district id are :', DistrictId)
                        });
                      /*  console.log('after append',data);*/
                    }
                })
            })
            $('#DOB').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
            //form validation using jquery
            $('#addemp').validate({
                errorClass: 'help-block animation-slideDown', // You can change the animation class for a different entrance animation - check animations page  
                errorElement: 'div',
                errorPlacement: function (error, e) {
                    e.parents('.form-group > div').append(error);
                },
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success has-error').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    e.closest('.form-group').removeClass('has-success has-error');
                    e.closest('.help-block').remove();
                },
                rules: {
                    'Name': {
                        required: true,
                    },

                    'state': {
                        required: true,
                    },

                    'District': {
                        required: true,
                    },
                    'DOB': {
                        required: true,
                    }
                },
                messages: {
                    'Name': 'Name missing',
                    'state': 'select state',
                    'District': 'select district',
                    'DOB': 'dob missing '
                }
            });
        });
    </script>
    
}

WebApplication2/Views/Employee/GetAllEmpDetails.cshtml
@model IEnumerable<WebApplication2.Models.EmpModel>

<p>
    @Html.ActionLink("Add Employee", "AddEmployee")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Empid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.City)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.Address)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.District)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            Action
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Empid)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    @*<td>
        @Html.DisplayFor(modelItem => item.City)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address)
    </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.state)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.District)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DOB)
    </td>
    <td>
        @Html.ActionLink("Edit", "EditEmpDetails", new { id = item.Empid }) |
        @Html.ActionLink("Delete", "DeleteEmp", new { id = item.Empid }, new { onclick = "return confirm('Are sure wants to delete?');" })
    </td>
</tr>
    }
</table>
@section Scripts {     }

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CRUD</p>
        </footer>
    </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-3.6.0.intellisense.js"></script>
    <!--<script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>-->
    @*<a href="~/Scripts/jquery-3.6.0.min.map">~/Scripts/jquery-3.6.0.min.map</a>*@
    <!--<script src="~/Scripts/jquery-3.6.0.slim.js"></script>
    <script src="~/Scripts/jquery-3.6.0.slim.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>-->
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @RenderSection("Scripts")
</body>
</html>